all:
		gcc -o rsa_assign_1 rsa_assign_1.c -lgmp
		gcc -o dh_assign_1 dh_assign_1.c -lm

rsa: 
		gcc -o rsa_assign_1 rsa_assign_1.c -lgmp 

dh:   
		gcc -o dh_assign_1 dh_assign_1.c -lm

clean:
		rm -f rsa_assign_1
		rm -f dh_assign_1